name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Octavio-CC
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando snake.svg"
          add: "github-contribution-grid-snake.svg"
